In [1]:
import polars as pl
import os
import kagglehub

/home/vinicius/Documents/Workspace/ml_data_engeneering/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [73]:
def check_primary_key(df:pl.DataFrame, cols:list[str]|str)->bool:
    return len(df) == len(df.unique(cols))

In [2]:
dataset_dir = "./dataset"
if not os.path.isdir(dataset_dir):
    os.mkdir(dataset_dir)

In [4]:
path = kagglehub.dataset_download(
    "olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

Downloading to /home/vinicius/.cache/kagglehub/datasets/olistbr/brazilian-ecommerce/2.archive...

100%|██████████| 42.6M/42.6M [00:02<00:00, 18.2MB/s]

Extracting files...

Path to dataset files: /home/vinicius/.cache/kagglehub/datasets/olistbr/brazilian-ecommerce/versions/2

In [5]:
os.listdir(path)

['olist_customers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'product_category_name_translation.csv']

In [7]:
csv_files = [os.path.join(path, f) for f in os.listdir(path) if os.path.isfile(os.path.join(path, f)) and f.endswith(".csv")]
len(csv_files)

9

In [11]:
from shutil import copy2

for file in csv_files:
    dst_path = os.path.join(
        dataset_dir,
        os.path.split(file)[-1]
    )
    copy2(src=file, dst=dst_path)

In [ ]:
customer_df = pl.read_csv(os.path.join(dataset_dir, 'olist_customers_dataset.csv'))
orders_df = pl.read_csv(os.path.join(dataset_dir,'olist_orders_dataset.csv'))
geolocation_df = pl.read_csv(os.path.join(dataset_dir,'olist_geolocation_dataset.csv'))
items_df = pl.read_csv(os.path.join(dataset_dir,'olist_order_items_dataset.csv'))
payments_df = pl.read_csv(os.path.join(dataset_dir,'olist_order_payments_dataset.csv'))
reviews_df = pl.read_csv(os.path.join(dataset_dir,'olist_order_reviews_dataset.csv'))
products_df = pl.read_csv(os.path.join(dataset_dir,'olist_products_dataset.csv'))
sellers_df = pl.read_csv(os.path.join(dataset_dir,'olist_sellers_dataset.csv'))
category_translation_df = pl.read_csv(os.path.join(dataset_dir,'product_category_name_translation.csv'))

# CUSTOMERS_DATASET:

- customer_df:
    - <u>customer_id</u>: char(32), 
    - customer_unique_id: char(32), 
    - customer_zip_code_prefix: float
    - customer_city: varchar(50),
    - customer_state: char(2)

In [17]:
customer_df.describe()

shape: (9, 6)
┌────────────┬─────────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ statistic  ┆ customer_id     ┆ customer_uniqu ┆ customer_zip_c ┆ customer_city  ┆ customer_state │
│ ---        ┆ ---             ┆ e_id           ┆ ode_prefix     ┆ ---            ┆ ---            │
│ str        ┆ str             ┆ ---            ┆ ---            ┆ str            ┆ str            │
│            ┆                 ┆ str            ┆ f64            ┆                ┆                │
╞════════════╪═════════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ count      ┆ 99441           ┆ 99441          ┆ 99441.0        ┆ 99441          ┆ 99441          │
│ null_count ┆ 0               ┆ 0              ┆ 0.0            ┆ 0              ┆ 0              │
│ mean       ┆ null            ┆ null           ┆ 35137.474583   ┆ null           ┆ null           │
│ std        ┆ null            ┆ null           ┆ 29797.938996   ┆ null           ┆ null           │
│ min        ┆ 00012a2ce6f8dcd ┆ 0000366f3b9a79 ┆ 1003.0         ┆ abadia dos     ┆ AC             │
│            ┆ a20d059ce984917 ┆ 92bf8c76cfdf32 ┆                ┆ dourados       ┆                │
│            ┆ …               ┆ 21…            ┆                ┆                ┆                │
│ 25%        ┆ null            ┆ null           ┆ 11347.0        ┆ null           ┆ null           │
│ 50%        ┆ null            ┆ null           ┆ 24416.0        ┆ null           ┆ null           │
│ 75%        ┆ null            ┆ null           ┆ 58900.0        ┆ null           ┆ null           │
│ max        ┆ ffffe8b65bbe308 ┆ ffffd2657e2aad ┆ 99990.0        ┆ zortea         ┆ TO             │
│            ┆ 7b653a978c870db ┆ 2907e67c3e9dae ┆                ┆                ┆                │
│            ┆ …               ┆ cb…            ┆                ┆                ┆                │
└────────────┴─────────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

In [18]:
customer_df.head()

shape: (5, 5)
┌────────────────────┬────────────────────┬───────────────────┬───────────────────┬────────────────┐
│ customer_id        ┆ customer_unique_id ┆ customer_zip_code ┆ customer_city     ┆ customer_state │
│ ---                ┆ ---                ┆ _prefix           ┆ ---               ┆ ---            │
│ str                ┆ str                ┆ ---               ┆ str               ┆ str            │
│                    ┆                    ┆ i64               ┆                   ┆                │
╞════════════════════╪════════════════════╪═══════════════════╪═══════════════════╪════════════════╡
│ 06b8999e2fba1a1fbc ┆ 861eff4711a542e4b9 ┆ 14409             ┆ franca            ┆ SP             │
│ 88172c00ba8b…      ┆ 3843c6dd7feb…      ┆                   ┆                   ┆                │
│ 18955e83d337fd6b2d ┆ 290c77bc529b7ac935 ┆ 9790              ┆ sao bernardo do   ┆ SP             │
│ ef6b18a428ac…      ┆ b93aa66c333d…      ┆                   ┆ campo             ┆                │
│ 4e7b3e00288586ebd0 ┆ 060e732b5b29e8181a ┆ 1151              ┆ sao paulo         ┆ SP             │
│ 8712fdd0374a…      ┆ 18229c7b0b2b…      ┆                   ┆                   ┆                │
│ b2b6027bc5c5109e52 ┆ 259dac757896d24d77 ┆ 8775              ┆ mogi das cruzes   ┆ SP             │
│ 9d4dc6358b12…      ┆ 02b9acbbff3f…      ┆                   ┆                   ┆                │
│ 4f2d8ab171c80ec836 ┆ 345ecd01c38d18a903 ┆ 13056             ┆ campinas          ┆ SP             │
│ 4f7c12e35b23…      ┆ 6ed96c73b8d0…      ┆                   ┆                   ┆                │
└────────────────────┴────────────────────┴───────────────────┴───────────────────┴────────────────┘

In [27]:
for col in customer_df.schema:
    if customer_df.schema[col] == pl.String:
        print(max(customer_df.with_columns(len_col=pl.col(col).str.len_chars())["len_col"]))

32
32
32
2

In [75]:
# check primary key:
check_primary_key(customer_df, "customer_id")

True

# ORDER_DATASET

- orders_df:
    - <u>order_id</u>: char(32)
    - customer_id: char(32) -> FK.customer_df.customer_id
    - order_status: varchar(20)
    - order_purchase_timestamp: timestamp
    - order_aproved_at: timestamp
    - order_delivered_carrier_date: timestamp
    - order_delivered_customer_date: timestamp
    - order_estimated_delivery_date: date

In [44]:
orders_df.describe()

shape: (9, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ order_id  ┆ customer_ ┆ order_sta ┆ … ┆ order_app ┆ order_del ┆ order_del ┆ order_es │
│ ---       ┆ ---       ┆ id        ┆ tus       ┆   ┆ roved_at  ┆ ivered_ca ┆ ivered_cu ┆ timated_ │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ rrier_dat ┆ stomer_da ┆ delivery │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ e         ┆ te        ┆ _date    │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 99441     ┆ 99441     ┆ 99441     ┆ … ┆ 99281     ┆ 97658     ┆ 96476     ┆ 99441    │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 160       ┆ 1783      ┆ 2965      ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ min       ┆ 00010242f ┆ 00012a2ce ┆ approved  ┆ … ┆ 2016-09-1 ┆ 2016-10-0 ┆ 2016-10-1 ┆ 2016-09- │
│           ┆ e8c5a6d1b ┆ 6f8dcda20 ┆           ┆   ┆ 5         ┆ 8         ┆ 1         ┆ 30       │
│           ┆ a2dd792cb ┆ d059ce984 ┆           ┆   ┆ 12:16:38  ┆ 10:34:01  ┆ 13:46:32  ┆ 00:00:00 │
│           ┆ 162…      ┆ 917…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ fffe41c64 ┆ ffffe8b65 ┆ unavailab ┆ … ┆ 2018-09-0 ┆ 2018-09-1 ┆ 2018-10-1 ┆ 2018-11- │
│           ┆ 501cc87c8 ┆ bbe3087b6 ┆ le        ┆   ┆ 3         ┆ 1         ┆ 7         ┆ 12       │
│           ┆ 01fd61db3 ┆ 53a978c87 ┆           ┆   ┆ 17:40:06  ┆ 19:48:28  ┆ 13:22:46  ┆ 00:00:00 │
│           ┆ f62…      ┆ 0db…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [48]:
orders_df.group_by("order_status").len().with_columns(prop=(pl.col("len")/len(orders_df)).round(4)).sort("order_status")

shape: (8, 3)
┌──────────────┬───────┬────────┐
│ order_status ┆ len   ┆ prop   │
│ ---          ┆ ---   ┆ ---    │
│ str          ┆ u32   ┆ f64    │
╞══════════════╪═══════╪════════╡
│ approved     ┆ 2     ┆ 0.0    │
│ canceled     ┆ 625   ┆ 0.0063 │
│ created      ┆ 5     ┆ 0.0001 │
│ delivered    ┆ 96478 ┆ 0.9702 │
│ invoiced     ┆ 314   ┆ 0.0032 │
│ processing   ┆ 301   ┆ 0.003  │
│ shipped      ┆ 1107  ┆ 0.0111 │
│ unavailable  ┆ 609   ┆ 0.0061 │
└──────────────┴───────┴────────┘

In [76]:
# check primary key:
check_primary_key(orders_df, "order_id")

True

# GEOLOCATION_DATASET

- geolocation_df:
    - geolocation_zip_code_prefix: integer
    - geolocation_lat: decimal(8, 6)
    - geolocation_lng: decimal(9, 6)
    - geolocation_city: varchar(50)
    - geolocation_state: char(2)

In [54]:
geolocation_df.describe()

shape: (9, 6)
┌────────────┬─────────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ statistic  ┆ geolocation_zip ┆ geolocation_la ┆ geolocation_ln ┆ geolocation_ci ┆ geolocation_st │
│ ---        ┆ _code_prefix    ┆ t              ┆ g              ┆ ty             ┆ ate            │
│ str        ┆ ---             ┆ ---            ┆ ---            ┆ ---            ┆ ---            │
│            ┆ f64             ┆ f64            ┆ f64            ┆ str            ┆ str            │
╞════════════╪═════════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ count      ┆ 1.000163e6      ┆ 1.000163e6     ┆ 1.000163e6     ┆ 1000163        ┆ 1000163        │
│ null_count ┆ 0.0             ┆ 0.0            ┆ 0.0            ┆ 0              ┆ 0              │
│ mean       ┆ 36574.166466    ┆ -21.176153     ┆ -46.390541     ┆ null           ┆ null           │
│ std        ┆ 30549.33571     ┆ 5.715866       ┆ 4.269748       ┆ null           ┆ null           │
│ min        ┆ 1001.0          ┆ -36.605374     ┆ -101.466766    ┆ * cidade       ┆ AC             │
│ 25%        ┆ 11075.0         ┆ -23.603545     ┆ -48.573137     ┆ null           ┆ null           │
│ 50%        ┆ 26530.0         ┆ -22.919377     ┆ -46.637879     ┆ null           ┆ null           │
│ 75%        ┆ 63504.0         ┆ -19.979614     ┆ -43.767703     ┆ null           ┆ null           │
│ max        ┆ 99990.0         ┆ 45.065933      ┆ 121.105394     ┆ óleo           ┆ TO             │
└────────────┴─────────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

In [59]:
# Check if geolocation_zip_code_prefix is float or int
if len(geolocation_df.filter(pl.col("geolocation_zip_code_prefix") % 1 != 0)) == 0:
    print("Integer")
else:
    print("Float")

Integer

In [77]:
# check if any columns is unique:
for col in geolocation_df.columns:
    print(f"{col} -> is_unique: {check_primary_key(geolocation_df, col)}")

geolocation_zip_code_prefix -> is_unique: False
geolocation_lat -> is_unique: False
geolocation_lng -> is_unique: False
geolocation_city -> is_unique: False
geolocation_state -> is_unique: False

In [78]:
# Check possible pk:
check_primary_key(geolocation_df, ["geolocation_zip_code_prefix", "geolocation_lat", "geolocation_lng"])

False

# ORDER ITEMS DATASET:

- items_df:
    - <u>order_id</u>: char(32) -> FK payment_df.order_id
    - <u>order_item_id</u>: int
    - product_id: char(32) -> FK product_df.product_id
    - seller_id : char(32) -> FK sellers_df.seller_id
    - shipping_limit_date: timestamp
    - price: decimal(10, 2)
    - freight_value: decimal(10, 2)

In [66]:
items_df.describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ order_id   ┆ order_item ┆ product_i ┆ seller_id ┆ shipping_ ┆ price     ┆ freight_v │
│ ---        ┆ ---        ┆ _id        ┆ d         ┆ ---       ┆ limit_dat ┆ ---       ┆ alue      │
│ str        ┆ str        ┆ ---        ┆ ---       ┆ str       ┆ e         ┆ f64       ┆ ---       │
│            ┆            ┆ f64        ┆ str       ┆           ┆ ---       ┆           ┆ f64       │
│            ┆            ┆            ┆           ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 112650     ┆ 112650.0   ┆ 112650    ┆ 112650    ┆ 112650    ┆ 112650.0  ┆ 112650.0  │
│ null_count ┆ 0          ┆ 0.0        ┆ 0         ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ mean       ┆ null       ┆ 1.197834   ┆ null      ┆ null      ┆ null      ┆ 120.65373 ┆ 19.99032  │
│            ┆            ┆            ┆           ┆           ┆           ┆ 9         ┆           │
│ std        ┆ null       ┆ 0.705124   ┆ null      ┆ null      ┆ null      ┆ 183.63392 ┆ 15.806405 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 8         ┆           │
│ min        ┆ 00010242fe ┆ 1.0        ┆ 00066f42a ┆ 0015a82c2 ┆ 2016-09-1 ┆ 0.85      ┆ 0.0       │
│            ┆ 8c5a6d1ba2 ┆            ┆ eeb9f3007 ┆ db000af6a ┆ 9         ┆           ┆           │
│            ┆ dd792cb162 ┆            ┆ 548bb9d3f ┆ aaf3ae2ec ┆ 00:15:34  ┆           ┆           │
│            ┆ …          ┆            ┆ 33c…      ┆ b05…      ┆           ┆           ┆           │
│ 25%        ┆ null       ┆ 1.0        ┆ null      ┆ null      ┆ null      ┆ 39.9      ┆ 13.08     │
│ 50%        ┆ null       ┆ 1.0        ┆ null      ┆ null      ┆ null      ┆ 74.99     ┆ 16.26     │
│ 75%        ┆ null       ┆ 1.0        ┆ null      ┆ null      ┆ null      ┆ 134.9     ┆ 21.15     │
│ max        ┆ fffe41c645 ┆ 21.0       ┆ fffe9eeff ┆ ffff564a4 ┆ 2020-04-0 ┆ 6735.0    ┆ 409.68    │
│            ┆ 01cc87c801 ┆            ┆ 12fcbd74a ┆ f9085cd26 ┆ 9         ┆           ┆           │
│            ┆ fd61db3f62 ┆            ┆ 2f2b007dd ┆ 170f47323 ┆ 22:35:08  ┆           ┆           │
│            ┆ …          ┆            ┆ e0c…      ┆ 937…      ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [79]:
check_primary_key(items_df, ["order_id", "order_item_id"])

True

# ORDER PAYMENTS DATASET:

- payments_df:
    - <u>order_id</u>: char(32)
    - <u>payment_sequential</u>: int
    - payment_type: varchar(50)
    - payment_installments: int
    - payment_value: decimal(10, 2)

In [70]:
payments_df.describe()

shape: (9, 6)
┌────────────┬──────────────────┬─────────────────┬──────────────┬─────────────────┬───────────────┐
│ statistic  ┆ order_id         ┆ payment_sequent ┆ payment_type ┆ payment_install ┆ payment_value │
│ ---        ┆ ---              ┆ ial             ┆ ---          ┆ ments           ┆ ---           │
│ str        ┆ str              ┆ ---             ┆ str          ┆ ---             ┆ f64           │
│            ┆                  ┆ f64             ┆              ┆ f64             ┆               │
╞════════════╪══════════════════╪═════════════════╪══════════════╪═════════════════╪═══════════════╡
│ count      ┆ 103886           ┆ 103886.0        ┆ 103886       ┆ 103886.0        ┆ 103886.0      │
│ null_count ┆ 0                ┆ 0.0             ┆ 0            ┆ 0.0             ┆ 0.0           │
│ mean       ┆ null             ┆ 1.092679        ┆ null         ┆ 2.853349        ┆ 154.10038     │
│ std        ┆ null             ┆ 0.706584        ┆ null         ┆ 2.687051        ┆ 217.494064    │
│ min        ┆ 00010242fe8c5a6d ┆ 1.0             ┆ boleto       ┆ 0.0             ┆ 0.0           │
│            ┆ 1ba2dd792cb162…  ┆                 ┆              ┆                 ┆               │
│ 25%        ┆ null             ┆ 1.0             ┆ null         ┆ 1.0             ┆ 56.79         │
│ 50%        ┆ null             ┆ 1.0             ┆ null         ┆ 1.0             ┆ 100.0         │
│ 75%        ┆ null             ┆ 1.0             ┆ null         ┆ 4.0             ┆ 171.84        │
│ max        ┆ fffe41c64501cc87 ┆ 29.0            ┆ voucher      ┆ 24.0            ┆ 13664.08      │
│            ┆ c801fd61db3f62…  ┆                 ┆              ┆                 ┆               │
└────────────┴──────────────────┴─────────────────┴──────────────┴─────────────────┴───────────────┘

In [84]:
check_primary_key(payments_df, ["order_id", "payment_sequential"])

True

# REVIEWS DATASET

- reviews_df:
    - <u>review_id</u>: char(32)
    - <u>order_id</u>: char(32) -> FK order_df.order_id
    - review_score: int
    - review_comment_title: varchar(255) CHARACTER SET utf8mb4
    - review_comment_message: varchar(2000) CHARACTER SET utf8mb4
    - review_creation_date: timestamp
    - review_answer_timestamp: timestamp

In [72]:
reviews_df.describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ review_id  ┆ order_id   ┆ review_sc ┆ review_co ┆ review_co ┆ review_cr ┆ review_an │
│ ---        ┆ ---        ┆ ---        ┆ ore       ┆ mment_tit ┆ mment_mes ┆ eation_da ┆ swer_time │
│ str        ┆ str        ┆ str        ┆ ---       ┆ le        ┆ sage      ┆ te        ┆ stamp     │
│            ┆            ┆            ┆ f64       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆           ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 99224      ┆ 99224      ┆ 99224.0   ┆ 11568     ┆ 40977     ┆ 99224     ┆ 99224     │
│ null_count ┆ 0          ┆ 0          ┆ 0.0       ┆ 87656     ┆ 58247     ┆ 0         ┆ 0         │
│ mean       ┆ null       ┆ null       ┆ 4.086421  ┆ null      ┆ null      ┆ null      ┆ null      │
│ std        ┆ null       ┆ null       ┆ 1.347579  ┆ null      ┆ null      ┆ null      ┆ null      │
│ min        ┆ 0001239bc1 ┆ 00010242fe ┆ 1.0       ┆           ┆
         ┆ 2016-10-0 ┆ 2016-10-0 │
│            ┆ de2e33cb58 ┆ 8c5a6d1ba2 ┆           ┆           ┆           ┆ 2         ┆ 7         │
│            ┆ 3967c2ca4c ┆ dd792cb162 ┆           ┆           ┆           ┆ 00:00:00  ┆ 18:32:28  │
│            ┆ …          ┆ …          ┆           ┆           ┆           ┆           ┆           │
│ 25%        ┆ null       ┆ null       ┆ 4.0       ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null       ┆ null       ┆ 5.0       ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null       ┆ null       ┆ 5.0       ┆ null      ┆ null      ┆ null      ┆ null      │
│ max        ┆ fffefe7a48 ┆ fffe41c645 ┆ 5.0       ┆ 🔟        ┆ 😡😡😡😡  ┆ 2018-08-3 ┆ 2018-10-2 │
│            ┆ d22f7b3204 ┆ 01cc87c801 ┆           ┆           ┆ 😡👎👎👎  ┆ 1         ┆ 9         │
│            ┆ 6421062219 ┆ fd61db3f62 ┆           ┆           ┆ 👎👎
     ┆ 00:00:00  ┆ 12:27:35  │
│            ┆ …          ┆ …          ┆           ┆           ┆ Empresa   ┆           ┆           │
│            ┆            ┆            ┆           ┆           ┆ sem       ┆           ┆           │
│            ┆            ┆            ┆           ┆           ┆ compro…   ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [86]:
# Check primary_key
check_primary_key(reviews_df, ["review_id", "order_id"])

True

In [87]:
len(reviews_df.filter(pl.col("review_score")%1!=0))

0

# PRODUCT DATASET

- product_df:
    - <u>product_id</u>: char(32)
    - product_category_name: varchar(200)
    - product_name_lenght: int
    - product_description_lenght: int 
    - product_photos_qty: int
    - product_weight_g: decimal(8, 2)
    - product_lenght_cm: decimal(8,2)
    - product_heigh_cm: decimal(8,2)
    - product_width_cm: decimal(8,2)

In [88]:
products_df.describe()

shape: (9, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ product_i ┆ product_c ┆ product_n ┆ … ┆ product_w ┆ product_l ┆ product_h ┆ product_ │
│ ---       ┆ d         ┆ ategory_n ┆ ame_lengh ┆   ┆ eight_g   ┆ ength_cm  ┆ eight_cm  ┆ width_cm │
│ str       ┆ ---       ┆ ame       ┆ t         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆ str       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 32951     ┆ 32341     ┆ 32341.0   ┆ … ┆ 32949.0   ┆ 32949.0   ┆ 32949.0   ┆ 32949.0  │
│ null_coun ┆ 0         ┆ 610       ┆ 610.0     ┆ … ┆ 2.0       ┆ 2.0       ┆ 2.0       ┆ 2.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ 48.476949 ┆ … ┆ 2276.4724 ┆ 30.815078 ┆ 16.937661 ┆ 23.19672 │
│           ┆           ┆           ┆           ┆   ┆ 88        ┆           ┆           ┆ 8        │
│ std       ┆ null      ┆ null      ┆ 10.245741 ┆ … ┆ 4282.0387 ┆ 16.914458 ┆ 13.637554 ┆ 12.07904 │
│           ┆           ┆           ┆           ┆   ┆ 31        ┆           ┆           ┆ 7        │
│ min       ┆ 00066f42a ┆ agro_indu ┆ 5.0       ┆ … ┆ 0.0       ┆ 7.0       ┆ 2.0       ┆ 6.0      │
│           ┆ eeb9f3007 ┆ stria_e_c ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 548bb9d3f ┆ omercio   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 33c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ 42.0      ┆ … ┆ 300.0     ┆ 18.0      ┆ 8.0       ┆ 15.0     │
│ 50%       ┆ null      ┆ null      ┆ 51.0      ┆ … ┆ 700.0     ┆ 25.0      ┆ 13.0      ┆ 20.0     │
│ 75%       ┆ null      ┆ null      ┆ 57.0      ┆ … ┆ 1900.0    ┆ 38.0      ┆ 21.0      ┆ 30.0     │
│ max       ┆ fffe9eeff ┆ utilidade ┆ 76.0      ┆ … ┆ 40425.0   ┆ 105.0     ┆ 105.0     ┆ 118.0    │
│           ┆ 12fcbd74a ┆ s_domesti ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2f2b007dd ┆ cas       ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ e0c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [89]:
check_primary_key(products_df, "product_id")

True

# SELLERS DATASET

- sellers_df:
    - <u>seller_id</u>: char(32)
    - seller_zip_code_prefix: int
    - seller_city: varchar(200) -> fix wrong value by geolocation zip code unique
    - seller_state: char(2)

In [90]:
sellers_df.describe()

shape: (9, 5)
┌────────────┬───────────────────────────────┬────────────────────────┬─────────────┬──────────────┐
│ statistic  ┆ seller_id                     ┆ seller_zip_code_prefix ┆ seller_city ┆ seller_state │
│ ---        ┆ ---                           ┆ ---                    ┆ ---         ┆ ---          │
│ str        ┆ str                           ┆ f64                    ┆ str         ┆ str          │
╞════════════╪═══════════════════════════════╪════════════════════════╪═════════════╪══════════════╡
│ count      ┆ 3095                          ┆ 3095.0                 ┆ 3095        ┆ 3095         │
│ null_count ┆ 0                             ┆ 0.0                    ┆ 0           ┆ 0            │
│ mean       ┆ null                          ┆ 32291.059451           ┆ null        ┆ null         │
│ std        ┆ null                          ┆ 32713.45383            ┆ null        ┆ null         │
│ min        ┆ 0015a82c2db000af6aaaf3ae2ecb0 ┆ 1001.0                 ┆ 04482255    ┆ AC           │
│            ┆ 5…                            ┆                        ┆             ┆              │
│ 25%        ┆ null                          ┆ 7094.0                 ┆ null        ┆ null         │
│ 50%        ┆ null                          ┆ 14940.0                ┆ null        ┆ null         │
│ 75%        ┆ null                          ┆ 65072.0                ┆ null        ┆ null         │
│ max        ┆ ffff564a4f9085cd26170f4732393 ┆ 99730.0                ┆ xaxim       ┆ SP           │
│            ┆ 7…                            ┆                        ┆             ┆              │
└────────────┴───────────────────────────────┴────────────────────────┴─────────────┴──────────────┘

In [91]:
check_primary_key(sellers_df, "seller_id")

True

In [96]:
print(
    sellers_df.filter(pl.col("seller_city").str.to_integer(strict=False).is_not_null())["seller_id"][0]
)
sellers_df.filter(pl.col("seller_city").str.to_integer(strict=False).is_not_null())

ceb7b4fb9401cd378de7886317ad1b47

shape: (1, 4)
┌─────────────────────────────────┬────────────────────────┬─────────────┬──────────────┐
│ seller_id                       ┆ seller_zip_code_prefix ┆ seller_city ┆ seller_state │
│ ---                             ┆ ---                    ┆ ---         ┆ ---          │
│ str                             ┆ i64                    ┆ str         ┆ str          │
╞═════════════════════════════════╪════════════════════════╪═════════════╪══════════════╡
│ ceb7b4fb9401cd378de7886317ad1b… ┆ 22790                  ┆ 04482255    ┆ RJ           │
└─────────────────────────────────┴────────────────────────┴─────────────┴──────────────┘

In [95]:
geolocation_df.filter(pl.col("geolocation_zip_code_prefix")==22790).unique("geolocation_city")

shape: (1, 5)
┌───────────────────────┬─────────────────┬─────────────────┬──────────────────┬───────────────────┐
│ geolocation_zip_code_ ┆ geolocation_lat ┆ geolocation_lng ┆ geolocation_city ┆ geolocation_state │
│ prefix                ┆ ---             ┆ ---             ┆ ---              ┆ ---               │
│ ---                   ┆ f64             ┆ f64             ┆ str              ┆ str               │
│ i64                   ┆                 ┆                 ┆                  ┆                   │
╞═══════════════════════╪═════════════════╪═════════════════╪══════════════════╪═══════════════════╡
│ 22790                 ┆ -23.011335      ┆ -43.450256      ┆ rio de janeiro   ┆ RJ                │
└───────────────────────┴─────────────────┴─────────────────┴──────────────────┴───────────────────┘

In [99]:
sellers_df = sellers_df.with_columns(
    seller_city = pl.when(pl.col("seller_city")=="04482255").then(
        pl.lit("rio de janeiro")
    ).otherwise(pl.col("seller_city"))
)
sellers_df.filter(pl.col("seller_id").str.contains("ceb7b4fb9401cd378de7886317ad1b47"))

shape: (1, 4)
┌─────────────────────────────────┬────────────────────────┬────────────────┬──────────────┐
│ seller_id                       ┆ seller_zip_code_prefix ┆ seller_city    ┆ seller_state │
│ ---                             ┆ ---                    ┆ ---            ┆ ---          │
│ str                             ┆ i64                    ┆ str            ┆ str          │
╞═════════════════════════════════╪════════════════════════╪════════════════╪══════════════╡
│ ceb7b4fb9401cd378de7886317ad1b… ┆ 22790                  ┆ rio de janeiro ┆ RJ           │
└─────────────────────────────────┴────────────────────────┴────────────────┴──────────────┘

# CATEGORY NAME TRANSLATION DATASET:

- category_translation:
    - <u>product_category_name</u>: varchar(200) -> FK product_df.product_category_name
    - product_category_name_english: varchar(200)

In [100]:
category_translation_df.describe()

shape: (9, 3)
┌────────────┬───────────────────────────┬───────────────────────────────┐
│ statistic  ┆ product_category_name     ┆ product_category_name_english │
│ ---        ┆ ---                       ┆ ---                           │
│ str        ┆ str                       ┆ str                           │
╞════════════╪═══════════════════════════╪═══════════════════════════════╡
│ count      ┆ 71                        ┆ 71                            │
│ null_count ┆ 0                         ┆ 0                             │
│ mean       ┆ null                      ┆ null                          │
│ std        ┆ null                      ┆ null                          │
│ min        ┆ agro_industria_e_comercio ┆ agro_industry_and_commerce    │
│ 25%        ┆ null                      ┆ null                          │
│ 50%        ┆ null                      ┆ null                          │
│ 75%        ┆ null                      ┆ null                          │
│ max        ┆ utilidades_domesticas     ┆ watches_gifts                 │
└────────────┴───────────────────────────┴───────────────────────────────┘

In [101]:
check_primary_key(category_translation_df, "product_category_name")

True